# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_merchant_option_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_ID = QtWidgets.QLabel(self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(80, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")

        self.label_Name = QtWidgets.QLabel(self.centralwidget)
        self.label_Name.setGeometry(QtCore.QRect(260, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Name.setFont(font)
        self.label_Name.setObjectName("label_Name")

        self.label_IDinTable = QtWidgets.QLabel(self.centralwidget)
        self.label_IDinTable.setGeometry(QtCore.QRect(120, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_IDinTable.setFont(font)
        self.label_IDinTable.setObjectName("label_IDinTable")

        self.lineEdit_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Name.setGeometry(QtCore.QRect(320, 50, 121, 31))
        self.lineEdit_Name.setText("")
        self.lineEdit_Name.setObjectName("lineEdit_Name")

        self.btn_modifyName = QtWidgets.QPushButton(self.centralwidget)
        self.btn_modifyName.setGeometry(QtCore.QRect(690, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_modifyName.setFont(font)
        self.btn_modifyName.setObjectName("btn_modifyName")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(170, 100, 551, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.btn_selling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_selling.setGeometry(QtCore.QRect(50, 160, 101, 41))
        self.btn_selling.setObjectName("btn_selling")

        self.btn_selled = QtWidgets.QPushButton(self.centralwidget)
        self.btn_selled.setGeometry(QtCore.QRect(50, 260, 101, 41))
        self.btn_selled.setObjectName("btn_selled")

        self.btn_modifyData = QtWidgets.QPushButton(self.centralwidget)
        self.btn_modifyData.setGeometry(QtCore.QRect(270, 390, 101, 41))
        self.btn_modifyData.setObjectName("btn_modifyData")

        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(490, 390, 111, 41))
        self.btn_back.setObjectName("btn_back")

        self.label_Password = QtWidgets.QLabel(self.centralwidget)
        self.label_Password.setGeometry(QtCore.QRect(450, 55, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Password.setFont(font)
        self.label_Password.setObjectName("label_Password")

        self.lineEdit_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(540, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setObjectName("lineEdit_Password")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "商家界面"))
        self.label_ID.setText(_translate("MainWindow", "ID："))
        self.label_Name.setText(_translate("MainWindow", "Name:"))
        self.label_IDinTable.setText(_translate("MainWindow", "ID_table"))
        self.btn_modifyName.setText(_translate("MainWindow", "修改"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "售价"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "库存/买家"))
        self.btn_selling.setText(_translate("MainWindow", "售出ing"))
        self.btn_selled.setText(_translate("MainWindow", "售出ed"))
        self.btn_modifyData.setText(_translate("MainWindow", "修改"))
        self.btn_back.setText(_translate("MainWindow", "返回"))
        self.label_Password.setText(_translate("MainWindow", "Password："))
